### ISSUE TITLE
Add a link to my awesome-anime-sources in readme

### ISSUE THREAD

**Issue by anshumanv** [freenode-anime/stuff#4]
I have a separate repo for aggregating anime related websites/apps [here](https://github.com/anshumanv/awesome-anime-sources). 
Probably we should give a link to the repo or [website](https://anshumanv.github.io/awesome-anime-sources/) in the readme so visitors and visit at ease.

Should I send a PR?

**Comment by mathu** [comment]
thanks for your interest, but I'm going to close this. a lot of the links in your repo are for streams/services that are not officially licensed - as far as our "officially endorsed" links go we want to stay above the table (and freenode ToS requires that we do). your offer is appreciated, though
